Add 7-Zip to prevent DMM "unknown method" error with 7z archives

diff --git a/dmm b/dmm
--- a/dmm
+++ b/dmm
@@ -20,6 +20,7 @@ MISSDEPS=0
 [ ! -e /usr/bin/curl ]     && echo 'Command curl not found'     && MISSDEPS=$((MISSDEPS+1))
 [ ! -e /usr/bin/find ]     && echo 'Command find not found'     && MISSDEPS=$((MISSDEPS+1))
 [ ! -e /bin/grep ]         && echo 'Command grep not found'     && MISSDEPS=$((MISSDEPS+1))
+[ ! -e /usr/bin/head ]     && echo 'Command head not found'     && MISSDEPS=$((MISSDEPS+1))
 [ ! -e /bin/mkdir ]        && echo 'Command mkdir not found'    && MISSDEPS=$((MISSDEPS+1))
 [ ! -e /usr/bin/realpath ] && echo 'Command realpath not found' && MISSDEPS=$((MISSDEPS+1))
 [ ! -e /bin/rm ]           && echo 'Command rm not found'       && MISSDEPS=$((MISSDEPS+1))
@@ -103,6 +104,17 @@ get_dotnet_version () {
   esac
 }
 
+get_7zip_version () {
+  case "${1}" in
+    local)
+      /usr/bin/head -1 "${DMM_PRFX}/drive_c/Program Files/7-Zip/readme.txt" | /usr/bin/cut -d\  -f2 | /bin/sed 's/\r//g'
+    ;;
+    remote)
+      /usr/bin/curl -s "https://www.7-zip.org/download.html" | /bin/grep "Download 7-Zip" | /usr/bin/head -1 | /usr/bin/cut -d\  -f3
+    ;;
+  esac
+}
+
 get_proton () {
   GEP_VRSN="GE-Proton$(get_lutris_version remote)"
   WGEC_URL="https://github.com/GloriousEggroll/wine-ge-custom/releases/download/${GEP_VRSN}/wine-lutris-${GEP_VRSN}-x86_64.tar.xz"
@@ -130,6 +142,19 @@ get_dotnet () {
   ( set -x; WINEPREFIX="${DMM_PRFX}" "${LUT_FLDR}/bin/wine64" "${TMP_FLDR}/dnr.exe" /install /quiet 2> /dev/null ) || exit 6
 }
 
+get_7zip () {
+  set -x
+  SVNZVRSN="$(get_7zip_version remote)"
+  DOTLESSV=${SVNZVRSN%.*}${SVNZVRSN#*.}
+  SVNZ_URL="https://www.7-zip.org/a/7z${DOTLESSV}-x64.exe"
+  exit 0
+  echo ' -> Downloading'
+  /usr/bin/curl -L "${SVNZ_URL}" -o "${TMP_FLDR}/7zi.exe" --progress-bar || exit 7
+  echo ' -> Installing'
+  LUT_FLDR="$(get_lutris_folder)" # Only to reduce output of set -x
+  ( set -x; WINEPREFIX="${DMM_PRFX}" "${LUT_FLDR}/bin/wine64" "${TMP_FLDR}/7zi.exe" /S 2> /dev/null ) || exit 8
+}
+
 get_dmm () {
   # Get the latest DivaModManager
   # Employ the same "trick" we did with GE-Proton
@@ -154,6 +179,7 @@ case "${1}" in
 
     check_install proton || get_proton
     check_install dotnet || get_dotnet
+    check_install 7zip || get_7zip
     check_install dmm || get_dmm
 
     # Find where the source files are
@@ -191,6 +217,9 @@ case "${1}" in
   ;;
   update|upgrade)
     case "${2}" in
+      7zip)
+        get_7zip
+      ;;
       dotnet)
         get_dotnet
       ;;
@@ -207,9 +236,10 @@ case "${1}" in
           printf '%-13s %8s %8s\n' '' 'Local' 'Upstream'
           printf '%-13s %8s %8s\n' 'GE-Proton' "$(get_lutris_version local)" "$(get_lutris_version remote)"
           printf '%-13s %8s %8s\n' '.NET Runtime' "$(get_dotnet_version local)" "$(get_dotnet_version remote)"
+          printf '%-13s %8s %8s\n' '7-Zip' "$(get_7zip_version local)" "$(get_7zip_version remote)"
         fi
         echo
-        echo "To upgrade components: $(/usr/bin/basename "${0}") upgrade <dotnet|proton>"
+        echo "To upgrade components: $(/usr/bin/basename "${0}") upgrade <7zip|dotnet|proton>"
       ;;
     esac
   ;;
